# frozen_string_literal: true

# https://github.com/dependabot/smoke-tests/blob/main/bundler/Gemfile

source "https://rubygems.org"

gem "rubocop", "1.55.1"
gem "toml-rb", "2.2.0"
gem 'rack', git: 'git@github.com:rack/rack.git', tag: '2.1.4'
