# frozen_string_literal: true

# https://github.com/dependabot/smoke-tests/blob/main/bundler/Gemfile

source "https://rubygems.org"

gem "rubocop", "0.76.0"
gem "toml-rb", "2.2.0"
gem 'rack', git: 'git@github.com:rack/rack.git', tag: 'v3.0.8'
